import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { parseMovieLens } from './lib/dataset';
import { evaluatePredictions, formatPercentage, getRecommendations, LIKE_THRESHOLD, wilsonInterval } from './lib/probability';

const MAX_SELECTIONS = 8;

function App() {
  const [data,setData]=useState(null), [loadError,setLoadError]=useState(''), [selections,setSelections]=useState([]), [query,setQuery]=useState(''), [active,setActive]=useState(null), [tab,setTab]=useState('recommend'), [evalResult,setEvalResult]=useState(null);
  useEffect(()=>{Promise.all([fetch(`${import.meta.env.BASE_URL}data/ratings.dat`).then(r=>r.ok?r.text():Promise.reject(new Error('Unable to load ratings.'))),fetch(`${import.meta.env.BASE_URL}data/movies.dat`).then(r=>r.ok?r.text():Promise.reject(new Error('Unable to load movies.')))]).then(([r,m])=>setData(parseMovieLens(r,m,LIKE_THRESHOLD))).catch(error=>setLoadError(error.message));},[]);
  const suggestions=useMemo(()=> data ? [...data.movies.values()].filter(m=>!selections.some(s=>s.id===m.id)&&m.title.toLowerCase().includes(query.toLowerCase())).slice(0, query?8:12) : [],[data,query,selections]);
  const recs=useMemo(()=>data?getRecommendations(data,selections):[],[data,selections]);
  const addMovie=m=>{if(selections.length<MAX_SELECTIONS) setSelections(s=>[...s,{id:m.id,rating:5}]); setQuery('');};
  if(loadError) return <main className="loading"><div className="orb">P</div><h1>ProbWatch</h1><p>We couldn’t load the local MovieLens data. Refresh the page to try again.</p></main>;
  if(!data) return <main className="loading"><div className="orb">P</div><h1>ProbWatch</h1><p>Loading one million ratings and building transparent evidence…</p></main>;
  return <main>
    <header><div className="brand"><span className="orb">P</span><span>ProbWatch</span><small>evidence, not magic</small></div><nav><button className={tab==='recommend'?'on':''} onClick={()=>setTab('recommend')}>Discover</button><button className={tab==='evaluate'?'on':''} onClick={()=>setTab('evaluate')}>Reality check</button><button className={tab==='learn'?'on':''} onClick={()=>setTab('learn')}>How it works</button></nav></header>
    {tab==='recommend' && <>
      <section className="hero"><p className="eyebrow">CONDITIONAL PROBABILITY, MADE WATCHABLE</p><h1>Find a movie with <em>evidence</em> behind it.</h1><p>Rate a few films you know. We estimate how often people who liked those same films also liked each recommendation.</p></section>
      <section className="picker card"><div><h2>Your watched films</h2><p className="muted">Choose 2–8. A rating of 4 or 5 counts as “liked.”</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a movie…" aria-label="Search movies"/><div className="chips">{suggestions.map(m=><button key={m.id} onClick={()=>addMovie(m)} className="movie-chip">+ {m.title}</button>)}</div><div className="selected">{selections.map(s=>{const m=data.movies.get(s.id);return <div className="selected-movie" key={s.id}><span>{m.title}</span><span className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setSelections(xs=>xs.map(x=>x.id===s.id?{...x,rating:n}:x))} className={n<=s.rating?'lit':''}>★</button>)}</span><button className="remove" onClick={()=>setSelections(xs=>xs.filter(x=>x.id!==s.id))}>×</button></div>})}</div>
      </section>
      {!selections.length ? <section className="empty card"><h2>Start with a few familiar movies</h2><p>Your selections form the condition in each probability estimate.</p></section> : !selections.some(x=>x.rating>=LIKE_THRESHOLD) ? <section className="empty card"><h2>Add at least one film you liked</h2><p>Move a rating to 4★ or 5★ to create your evidence group.</p></section> : <section className="results"><div className="result-title"><div><p className="eyebrow">YOUR EVIDENCE-BASED SHORTLIST</p><h2>Recommendations, with the uncertainty included</h2></div><span>{selections.filter(x=>x.rating>=LIKE_THRESHOLD).length} liked films observed</span></div><div className="grid">{recs.map(r=><article className="rec card" key={r.id}><div className="rec-top"><span className="badge">LIKELY TO LIKE</span><button onClick={()=>setActive(r)}>See evidence →</button></div><h3>{r.title}</h3><p className="prob">{formatPercentage(r.probability)} <small>estimated chance</small></p><div className="range"><span style={{left:`${r.lowerBound*100}%`,width:`${(r.upperBound-r.lowerBound)*100}%`}}></span><i style={{left:`${r.probability*100}%`}}></i></div><p className="interval">95% range: {formatPercentage(r.lowerBound)}–{formatPercentage(r.upperBound)}</p><p className="muted">{r.successes} likes in {r.observations} comparable ratings</p></article>)}</div></section>}
      {active&&<div className="modal-back" onClick={()=>setActive(null)}><aside className="modal card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><p className="eyebrow">THE EVIDENCE FOR</p><h2>{active.title}</h2><p className="bigformula">P(like {active.title} | liked your selected films)</p><div className="equation"><b>{active.successes}</b><span>people liked it</span><b>÷</b><b>{active.observations}</b><span>comparable ratings</span><b>=</b><strong>{formatPercentage(active.probability)}</strong></div><p>For every film you rated 4★ or 5★, we find MovieLens users who also liked it. Each time one of those users rated this film, it becomes one observation. The estimate pools those observations.</p><div className="notice">The 95% range ({formatPercentage(active.lowerBound)}–{formatPercentage(active.upperBound)}) is a Wilson confidence interval: a wider range means less evidence. People can appear in more than one condition, so this is a transparent heuristic—not a causal claim.</div></aside></div>}
    </>}
    {tab==='evaluate' && <section className="page"><p className="eyebrow">PREDICTIONS SHOULD FACE REALITY</p><h1>Hold-out evaluation</h1><p className="lede">We hide each test user’s two latest ratings, estimate them from earlier liked films, then compare the prediction with the actual rating. The test user is excluded from evidence counts.</p><button className="primary" onClick={()=>setEvalResult(evaluatePredictions(data))}>Run deterministic evaluation</button>{evalResult&&<><div className="metrics"><div className="card"><b>{evalResult.tests.length}</b><span>held-out predictions</span></div><div className="card"><b>{formatPercentage(evalResult.accuracy)}</b><span>like / not-like accuracy</span></div><div className="card"><b>{evalResult.brier.toFixed(3)}</b><span>Brier score (lower is better)</span></div></div><div className="card calibration"><h2>Calibration-style check</h2><p className="muted">Within each probability band, did the observed like rate resemble what we predicted?</p>{evalResult.bins.map(b=><div className="bin" key={b.label}><span>{b.label}</span><div><i style={{width:`${b.predicted*100}%`}}></i><em style={{width:`${b.observed*100}%`}}></em></div><small>predicted {formatPercentage(b.predicted)} · actual {formatPercentage(b.observed)} · n={b.count}</small></div>)}<p className="legend"><i></i> predicted probability <em></em> actual like rate</p></div></>}</section>}
    {tab==='learn' && <section className="page learn"><p className="eyebrow">NO BLACK BOX</p><h1>The maths in ProbWatch</h1><div className="card"><h2>1. Empirical conditional probability</h2><p>For a candidate movie M and a liked seed S: <code>P(like M | liked S) = count(liked S and liked M) / count(liked S and rated M)</code>. We pool these counts across your liked seeds to give recommendations more evidence.</p><h2>2. Uncertainty, not false precision</h2><p>Each card uses a 95% Wilson interval for a proportion. Its width shrinks roughly with <code>1 / √n</code>: quadrupling comparable ratings approximately halves sampling uncertainty.</p><div className="sample-demo">{[12,48,192].map(n=>{const [a,b]=wilsonInterval(Math.round(.7*n),n);return <div key={n}><b>n = {n}</b><span className="range"><i style={{left:`${a*100}%`,width:`${(b-a)*100}%`}}></i></span><small>{formatPercentage(a)}–{formatPercentage(b)}</small></div>})}</div><h2>3. Important limits</h2><p>These ratings are historical opinions from MovieLens 1M (2003), not a representative sample of everyone today. Ratings are not independent, pooled seeds can overlap, and “like” means 4★ or 5★. This is a learning-focused association model, not a claim that one movie causes enjoyment of another.</p></div></section>}
    <footer>Built from MovieLens 1M · deterministic calculations · no embeddings or opaque ML</footer>
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
